# Generated by Django 5.1.1 on 2024-09-29 16:47

import center_mgmt.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('center_id', models.CharField(default=center_mgmt.models.generate_uuid, editable=False, max_length=7, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('date_last_updated', models.DateTimeField(blank=True, default=None)),
                ('ETA', models.DateTimeField(blank=True, default=None)),
                ('in_schedule', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(choices=[(0, 'Low'), (50, 'Mid'), (100, 'High')], default=0)),
                ('driver', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='centers', to='driver_mgmt.driver')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lat', 'long'), name='unique_lat_long_center')],
            },
        ),
    ]
